### ISSUE TITLE
Greenlock / LE version no longer supported

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/get-lets-encrypt-servers#2]
In the `dev` branch:
```sh
~/gh/michielbdejong/get-lets-encrypt-servers $ node test.js 


=== WARNING ===

Due to versioning issues the 'staging' option is deprecated.
Please specify the full url and version.

For APIs add:
	, "version": "v01"
	, "server": "https://acme-staging.api.letsencrypt.org/directory"

For the CLI add:
	--acme-url 'https://acme-staging.api.letsencrypt.org/directory' \
	--acme-version 'v01' \



=== WARNING ===

Let's Encrypt v1 is deprecated.
Please update to Let's Encrypt v2 (ACME draft 12)

[greenlock/lib/middleware.js] created middleware
[le-store-certbot]
[le-store-certbot]
[greenlock/lib/core.js] checkAsync failed to find certificates
[le-store-certbot] accountId: null
deprecation notice: new signature for signJws(keypair, header, protect, payload)
(node:41156) UnhandledPromiseRejectionWarning: Error: Registration request failed: {
  "type": "urn:acme:error:unauthorized",
  "detail": "Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.",
  "status": 403
}
    at handleErr (/Users/michiel/gh/michielbdejong/get-lets-encrypt-servers/node_modules/le-acme-core/lib/register-new-account.js:105:17)
    at getTerms (/Users/michiel/gh/michielbdejong/get-lets-encrypt-servers/node_modules/le-acme-core/lib/register-new-account.js:32:16)
    at Request._callback (/Users/michiel/gh/michielbdejong/get-lets-encrypt-servers/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/Users/michiel/gh/michielbdejong/get-lets-encrypt-servers/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (/Users/michiel/gh/michielbdejong/get-lets-encrypt-servers/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/Users/michiel/gh/michielbdejong/get-lets-encrypt-servers/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
(node:41156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michielbdejong** [comment]
Fixing this in https://github.com/michielbdejong/get-lets-encrypt-servers/tree/rewrite-ts-greenlock-4
Also taking the opportunity to switch to typescript, and then I'll add the localhost option with self-signed cert, for use in https://github.com/michielbdejong/solid-app-kit/issues/1
